name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - Melvin  # Deploys when you push to Melvin branch
      - master  # Also deploys from master if you merge
    paths:
      - 'backend/**'
      - '.github/workflows/azure-deploy.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: powerguard-backend    # Set this to your app name
  NODE_VERSION: '20.x'                     # Set to Node.js version you're using
  WORKING_DIRECTORY: backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json

    - name: Install dependencies
      run: |
        cd ${{ env.WORKING_DIRECTORY }}
        npm ci

    - name: Generate Prisma Client
      run: |
        cd ${{ env.WORKING_DIRECTORY }}
        npx prisma generate

    - name: Build application
      run: |
        cd ${{ env.WORKING_DIRECTORY }}
        npm run build

    - name: Create deployment package
      run: |
        cd ${{ env.WORKING_DIRECTORY }}
        mkdir -p deploy
        cp -r dist deploy/
        cp -r node_modules deploy/
        cp -r prisma deploy/
        cp package*.json deploy/
        cd deploy
        zip -r ../deploy.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.WORKING_DIRECTORY }}/deploy.zip
